
import { StyleSheet } from '@react-pdf/renderer';

export const cardStyles = StyleSheet.create({
  // User Info Card - Professional Design
  userInfo: {
    marginBottom: 35,
    padding: 30,
    backgroundColor: '#F8FAFF',
    borderRadius: 20,
    borderWidth: 4,
    borderColor: '#2E7DFF',
    borderLeftWidth: 8,
    borderLeftColor: '#FFB800',
  },
  userInfoTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#1A1F36',
    textAlign: 'center',
  },
  userInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  userInfoItem: {
    width: '48%',
    marginBottom: 18,
  },
  userInfoLabel: {
    fontSize: 13,
    color: '#6B7280',
    marginBottom: 6,
    fontWeight: 'bold',
  },
  userInfoValue: {
    fontSize: 15,
    color: '#1A1F36',
    fontWeight: 'bold',
  },
  
  // Portfolio At a Glance - Enhanced Visual Impact
  portfolioGlance: {
    marginBottom: 40,
    padding: 35,
    backgroundColor: '#FFF8E7',
    borderRadius: 20,
    borderWidth: 5,
    borderColor: '#FFB800',
  },
  glanceTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 35,
    color: '#1A1F36',
  },
  glanceGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    marginBottom: 30,
  },
  glanceCard: {
    width: '23%',
    backgroundColor: '#FFFFFF',
    padding: 25,
    borderRadius: 18,
    borderWidth: 4,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    marginBottom: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  glanceLabel: {
    fontSize: 13,
    color: '#6B7280',
    marginBottom: 10,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  glanceValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1A1F36',
    textAlign: 'center',
  },
  glanceSubtext: {
    fontSize: 12,
    color: '#00B47B',
    textAlign: 'center',
    marginTop: 8,
    fontWeight: 'bold',
  },
  
  // Performance Section - Enhanced Design
  performanceSection: {
    backgroundColor: '#F0FDF4',
    padding: 30,
    borderRadius: 18,
    borderWidth: 5,
    borderColor: '#00B47B',
    marginTop: 25,
  },
  performanceTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1A1F36',
    textAlign: 'center',
    marginBottom: 25,
  },
  performanceGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  performanceItem: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 15,
    minWidth: '22%',
    borderWidth: 3,
    borderColor: '#00B47B',
  },
  performanceLabel: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 8,
    fontWeight: 'bold',
  },
  performanceValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#00B47B',
  },
  
  // AI Insight Section - Premium Enhancement
  aiInsight: {
    marginBottom: 40,
    padding: 35,
    backgroundColor: '#FFF8E7',
    borderRadius: 20,
    borderWidth: 5,
    borderColor: '#FFB800',
  },
  aiInsightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 25,
  },
  aiInsightIcon: {
    width: 36,
    height: 36,
    backgroundColor: '#FFB800',
    borderRadius: 18,
    marginRight: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiInsightIconText: {
    fontSize: 20,
    color: 'white',
    fontWeight: 'bold',
  },
  aiInsightTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1A1F36',
    flex: 1,
  },
  aiInsightContent: {
    backgroundColor: '#FFFFFF',
    padding: 25,
    borderRadius: 18,
    borderLeftWidth: 8,
    borderLeftColor: '#FFB800',
  },
  aiInsightText: {
    fontSize: 15,
    color: '#1A1F36',
    lineHeight: 1.8,
    marginBottom: 18,
  },
  aiInsightHighlight: {
    fontSize: 14,
    color: '#00B47B',
    fontWeight: 'bold',
  },
  percentileBadge: {
    backgroundColor: '#FFB800',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 8,
    alignSelf: 'flex-start',
    marginTop: 15,
  },
  percentileBadgeText: {
    color: '#1A1F36',
    fontWeight: 'bold',
    fontSize: 13,
  },
  
  // Summary Cards - Professional Layout
  summaryGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    marginTop: 30,
  },
  summaryCard: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    padding: 25,
    borderRadius: 18,
    borderWidth: 4,
    borderColor: '#E5E7EB',
    marginBottom: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  summaryTitle: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 8,
    fontWeight: 'bold',
  },
  summaryValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1A1F36',
  },
  summarySubtext: {
    fontSize: 13,
    color: '#00B47B',
    marginTop: 6,
    fontWeight: 'bold',
  },
});
