import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
  // ---------- PAGE ----------
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 28,
    fontFamily: 'Helvetica',
    fontSize: 11,
    position: 'relative',
    minHeight: '100%',
  },

  // ---------- WATERMARK ----------
  watermark: {
    position: 'absolute',
    top: '38%',
    left: 0,
    right: 0,
    textAlign: 'center',
    opacity: 0.055,
    fontSize: 80,
    color: '#2E7DFF',
    fontWeight: 700,
    zIndex: -1,
  },

  // ---------- HEADER ----------
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 34,
    paddingBottom: 22,
    borderBottomWidth: 3,
    borderBottomColor: '#2E7DFF',
    backgroundColor: '#F8FAFF',
    padding: 22,
    borderRadius: 16,
    borderWidth: 1.2,
    borderColor: '#E5E7EB',
  },
  logoSection: { flexDirection: 'column', alignItems: 'flex-start' },
  mainLogo: { flexDirection: 'row', alignItems: 'center', marginBottom: 7 },
  sipBreweryLogo: { width: 55, height: 55, marginRight: 14 },
  brandingText: { flexDirection: 'column' },
  companyName: { fontSize: 32, fontWeight: 700, color: '#1A1F36', marginBottom: 3 },
  tagline: { fontSize: 13, color: '#2E7DFF', fontStyle: 'italic', fontWeight: 700 },
  trademarkSection: { flexDirection: 'row', alignItems: 'center', marginTop: 7 },
  trademarkText: { fontSize: 10, color: '#6B7280', marginRight: 7 },
  equisculptBrand: { flexDirection: 'row', alignItems: 'center' },
  equisculptLogo: { width: 20, height: 20, marginRight: 6 },
  equisculptText: { fontSize: 12, color: '#1A1F36', fontWeight: 700 },
  headerInfo: { flexDirection: 'column', alignItems: 'flex-end' },
  generatedDate: { fontSize: 12, color: '#1A1F36', fontWeight: 700, marginBottom: 3 },
  regulatoryInfo: { fontSize: 10.5, color: '#6B7280' },

  // ---------- TITLES & SECTION HEADERS ----------
  statementTitle: {
    fontSize: 28,
    fontWeight: 700,
    textAlign: 'center',
    marginBottom: 26,
    color: '#FFFFFF',
    backgroundColor: '#2E7DFF',
    padding: 13,
    borderRadius: 9,
    borderWidth: 2.5,
    borderColor: '#1E40AF',
    letterSpacing: 0.2,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 700,
    marginBottom: 22,
    color: '#FFFFFF',
    backgroundColor: '#2E7DFF',
    padding: 12,
    borderRadius: 9,
    textAlign: 'center',
    borderWidth: 2.5,
    borderColor: '#1E40AF',
  },

  // ---------- USER INFO CARD ----------
  userInfo: {
    marginBottom: 24,
    padding: 17,
    backgroundColor: '#F8FAFF',
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#2E7DFF',
    borderLeftWidth: 6,
    borderLeftColor: '#FFB800',
  },
  userInfoTitle: {
    fontSize: 16,
    fontWeight: 700,
    marginBottom: 12,
    color: '#1A1F36',
    textAlign: 'center',
    letterSpacing: 0.18,
  },
  userInfoGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  userInfoItem: { width: '48%', marginBottom: 12 },
  userInfoLabel: { fontSize: 10.5, color: '#6B7280', marginBottom: 3, fontWeight: 700 },
  userInfoValue: { fontSize: 12.3, color: '#1A1F36', fontWeight: 700 },

  // ---------- PORTFOLIO AT A GLANCE ----------
  portfolioGlance: {
    marginBottom: 26,
    padding: 21,
    backgroundColor: '#FFF8E7',
    borderRadius: 15,
    borderWidth: 3,
    borderColor: '#FFB800',
  },
  glanceTitle: {
    fontSize: 18,
    fontWeight: 700,
    textAlign: 'center',
    marginBottom: 17,
    color: '#1A1F36',
    letterSpacing: 0.2,
  },
  glanceGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  glanceCard: {
    width: '23%',
    backgroundColor: '#FFFFFF',
    padding: 11,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    marginBottom: 7,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2.5,
  },
  glanceLabel: {
    fontSize: 10.5,
    color: '#6B7280',
    marginBottom: 4,
    textAlign: 'center',
    fontWeight: 700,
  },
  glanceValue: {
    fontSize: 16,
    fontWeight: 700,
    color: '#1A1F36',
    textAlign: 'center',
  },
  glanceSubtext: {
    fontSize: 9,
    color: '#00B47B',
    textAlign: 'center',
    marginTop: 3,
    fontWeight: 700,
  },

  // ---------- AI INSIGHT ----------
  aiInsight: {
    marginBottom: 22,
    padding: 19,
    backgroundColor: '#FFF8E7',
    borderRadius: 14,
    borderWidth: 3,
    borderColor: '#FFB800',
  },
  aiInsightHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  aiInsightIcon: {
    width: 22,
    height: 22,
    backgroundColor: '#FFB800',
    borderRadius: 11,
    marginRight: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiInsightIconText: { fontSize: 12, color: 'white', fontWeight: 700 },
  aiInsightTitle: { fontSize: 13.5, fontWeight: 700, color: '#1A1F36', flex: 1 },
  aiInsightContent: {
    backgroundColor: '#FFFFFF',
    padding: 10,
    borderRadius: 9,
    borderLeftWidth: 5,
    borderLeftColor: '#FFB800',
  },
  aiInsightText: { fontSize: 11.5, color: '#1A1F36', lineHeight: 1.45, marginBottom: 6 },
  aiInsightHighlight: { fontSize: 11, color: '#00B47B', fontWeight: 700 },
  percentileBadge: {
    backgroundColor: '#FFB800',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    alignSelf: 'flex-start',
    marginTop: 7,
  },
  percentileBadgeText: { color: '#1A1F36', fontWeight: 700, fontSize: 10.5 },

  // ---------- HOLDINGS TABLE ----------
  section: { marginBottom: 18 },
  tableContainer: {
    borderRadius: 9,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#E5E7EB',
    marginBottom: 12,
  },
  tableHeader: { flexDirection: 'row', backgroundColor: '#1A1F36', padding: 10 },
  tableHeaderCell: { fontSize: 10.3, color: '#FFFFFF', fontWeight: 700, paddingHorizontal: 7 },
  tableRow: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    padding: 9,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  tableRowAlternate: {
    flexDirection: 'row',
    backgroundColor: '#F9FAFB',
    padding: 9,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  tableRowHighlight: {
    flexDirection: 'row',
    backgroundColor: '#FEF3C7',
    padding: 9,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    borderLeftWidth: 5,
    borderLeftColor: '#FFB800',
  },
  tableCell: { fontSize: 9.7, color: '#1A1F36', paddingHorizontal: 7 },
  tableCellBold: { fontSize: 9.7, color: '#1A1F36', paddingHorizontal: 7, fontWeight: 700 },
  tableCellGreen: { fontSize: 9.7, color: '#00B47B', paddingHorizontal: 7, fontWeight: 700 },
  tableCellRed: { fontSize: 9.7, color: '#EF4444', paddingHorizontal: 7, fontWeight: 700 },

  // ---------- TRANSACTION/UPCOMING SIP/REWARDS ----------
  transactionSection: {
    marginBottom: 15,
    padding: 12,
    backgroundColor: '#F8FAFF',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#2E7DFF',
  },
  transactionTitle: {
    fontSize: 12.7,
    fontWeight: 700,
    color: '#1A1F36',
    marginBottom: 7,
    textAlign: 'center',
  },
  transactionTable: { borderRadius: 7, overflow: 'hidden', borderWidth: 1.2, borderColor: '#E5E7EB' },
  upcomingSipSection: {
    marginBottom: 15,
    padding: 12,
    backgroundColor: '#F0FDF4',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#00B47B',
  },
  upcomingSipTitle: {
    fontSize: 12.7,
    fontWeight: 700,
    color: '#1A1F36',
    marginBottom: 7,
    textAlign: 'center',
  },

  // ---------- REWARDS & CAPITAL GAINS ----------
  rewardsSection: { 
    marginBottom: 15,
    padding: 12,
    backgroundColor: '#F0FDF4',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#00B47B',
  },
  rewardsTitle: { fontSize: 12.7, fontWeight: 700, color: '#1A1F36', marginBottom: 7 },
  capitalGainsSection: { 
    marginBottom: 15,
    padding: 12,
    backgroundColor: '#F8FAFF',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#2E7DFF',
  },
  capitalGainsTitle: { fontSize: 12.7, fontWeight: 700, color: '#1A1F36', marginBottom: 7 },

  // ---------- CHARTS ----------
  chartsSection: { marginBottom: 20 },
  chartsTitle: { fontSize: 12.7, fontWeight: 700, color: '#1A1F36', marginBottom: 7 },
  chartImage: { width: 350, height: 120, margin: 'auto', marginBottom: 12 },

  // ---------- FOOTER & DISCLAIMER ----------
  disclaimer: {
    marginTop: 24,
    padding: 13,
    backgroundColor: '#FEF2F2',
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#FECACA',
    borderLeftWidth: 5,
    borderLeftColor: '#EF4444',
    fontSize: 9.5,
    color: '#7F1D1D',
    lineHeight: 1.33,
  },
  disclaimerTitle: {
    fontSize: 10,
    fontWeight: 700,
    color: '#7F1D1D',
    marginBottom: 5,
  },
  disclaimerText: {
    fontSize: 9.5,
    color: '#7F1D1D',
    lineHeight: 1.33,
  },
  footer: {
    marginTop: 18,
    backgroundColor: '#F8FAFF',
    padding: 15,
    borderRadius: 9,
    borderTopWidth: 3,
    borderTopColor: '#2E7DFF',
    fontSize: 10,
  },
  footerContent: { flexDirection: 'row', justifyContent: 'space-between' },
  footerLeft: { flex: 2 },
  footerRight: { flex: 1, alignItems: 'flex-end' },
  footerBranding: { marginBottom: 5 },
  footerCompany: { fontSize: 11, color: '#2E7DFF', fontWeight: 700 },
  footerTrademark: { fontSize: 9, color: '#6B7280' },
  footerContact: { fontSize: 10, color: '#6B7280', marginBottom: 2.5 },
  footerGenerated: { fontSize: 10, color: '#6B7280', fontWeight: 700 },
  confidentialBadge: {
    backgroundColor: '#2E7DFF',
    borderRadius: 4,
    paddingVertical: 3,
    paddingHorizontal: 8,
    marginTop: 5,
  },
  footerConfidential: { fontSize: 9, color: '#FFFFFF', fontWeight: 700 },

  // ---------- MISSING STYLES ----------
  regulatoryBadge: {
    backgroundColor: '#2E7DFF',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  regulatoryBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 700,
    textAlign: 'center',
  },
  statementPeriod: {
    backgroundColor: '#F0F9FF',
    padding: 8,
    borderRadius: 6,
    marginBottom: 15,
    textAlign: 'center',
    fontSize: 10,
    color: '#1E40AF',
  },
  progressBarContainer: {
    backgroundColor: '#E5E7EB',
    height: 8,
    borderRadius: 4,
    marginTop: 8,
    overflow: 'hidden',
  },
  progressBarFill: {
    backgroundColor: '#FFB800',
    height: '100%',
    borderRadius: 4,
  },
  summaryGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    gap: 15,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: '#F8FAFF',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  summaryTitle: {
    fontSize: 10,
    color: '#6B7280',
    fontWeight: 700,
    textAlign: 'center',
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 14,
    color: '#2E7DFF',
    fontWeight: 700,
    textAlign: 'center',
  },
  summarySubtext: {
    fontSize: 9,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 2,
  },
  xirrExplanation: {
    backgroundColor: '#F0F9FF',
    padding: 15,
    borderRadius: 8,
    marginTop: 20,
    borderLeftWidth: 4,
    borderLeftColor: '#2E7DFF',
  },
  xirrNote: {
    fontSize: 10,
    color: '#1E40AF',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  goalProgress: {
    backgroundColor: '#F0FDF4',
    padding: 15,
    borderRadius: 8,
    marginTop: 15,
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  goalProgressTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: '#166534',
    marginBottom: 10,
    textAlign: 'center',
  },
  goalProgressContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  goalProgressItem: {
    flex: 1,
    alignItems: 'center',
  },
  goalProgressLabel: {
    fontSize: 10,
    color: '#6B7280',
    marginBottom: 4,
  },
  goalProgressValue: {
    fontSize: 12,
    fontWeight: 700,
    color: '#166534',
  },
  aiBadge: {
    backgroundColor: '#2E7DFF',
    borderRadius: 20,
    paddingVertical: 4,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  aiBadgeIcon: {
    fontSize: 14,
    marginRight: 6,
  },
  aiBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 700,
  },
  glanceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 17,
  },
  glanceCardPrimary: {
    borderColor: '#FFB800',
  },
  glanceCardSuccess: {
    borderColor: '#00B47B',
  },
  glanceCardWarning: {
    borderColor: '#FFB800',
  },
  glanceCardInfo: {
    borderColor: '#2E7DFF',
  },
  glanceIcon: {
    fontSize: 16,
    marginBottom: 8,
  },

  // ---------- AVATAR STYLES ----------
  avatarCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#2E7DFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  avatarInitials: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 700,
  },
  verifiedBadge: {
    backgroundColor: '#00B47B',
    borderRadius: 10,
    paddingVertical: 2,
    paddingHorizontal: 6,
    marginLeft: 8,
  },
  verifiedBadgeText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: 700,
  },

  // ---------- BRAND COLORS ----------
  primaryBlue: { color: '#2E7DFF' },
  primaryGold: { color: '#FFB800' },
  primaryGreen: { color: '#00B47B' },
});