
import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 30,
    fontFamily: 'Helvetica',
  },
  header: {
    flexDirection: 'row',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: '#2E7DFF',
  },
  logoContainer: {
    flex: 1,
  },
  companyInfo: {
    flex: 2,
    alignItems: 'flex-end',
  },
  companyName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1A1F36',
    marginBottom: 5,
  },
  tagline: {
    fontSize: 12,
    color: '#2E7DFF',
    fontStyle: 'italic',
  },
  statementTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1A1F36',
    textAlign: 'center',
    marginVertical: 20,
    backgroundColor: '#F5F8FF',
    padding: 10,
  },
  userInfo: {
    backgroundColor: '#F5F8FF',
    padding: 15,
    marginBottom: 20,
    borderRadius: 5,
  },
  userInfoTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1A1F36',
    marginBottom: 10,
  },
  userInfoRow: {
    flexDirection: 'row',
    marginBottom: 5,
  },
  userInfoLabel: {
    fontSize: 10,
    color: '#666666',
    width: 100,
  },
  userInfoValue: {
    fontSize: 10,
    color: '#1A1F36',
    fontWeight: 'bold',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1A1F36',
    marginBottom: 10,
    backgroundColor: '#FFF6E7',
    padding: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#FFB800',
  },
  table: {
    display: 'flex',
    width: 'auto',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  tableRow: {
    margin: 'auto',
    flexDirection: 'row',
  },
  tableColHeader: {
    width: '20%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#2E7DFF',
    padding: 8,
  },
  tableCol: {
    width: '20%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 8,
  },
  tableCellHeader: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  tableCell: {
    fontSize: 9,
    color: '#1A1F36',
  },
  summaryCard: {
    backgroundColor: '#F0F9FF',
    padding: 15,
    marginBottom: 15,
    borderRadius: 5,
    borderLeftWidth: 4,
    borderLeftColor: '#00B47B',
  },
  summaryTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#1A1F36',
    marginBottom: 5,
  },
  summaryValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#00B47B',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 8,
    color: '#666666',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
  },
  disclaimer: {
    fontSize: 8,
    color: '#666666',
    textAlign: 'justify',
    marginBottom: 10,
    backgroundColor: '#FFFBEB',
    padding: 10,
  },
  aiInsight: {
    backgroundColor: '#F3E8FF',
    padding: 12,
    marginBottom: 15,
    borderRadius: 5,
    borderLeftWidth: 4,
    borderLeftColor: '#8B5CF6',
  },
  aiInsightTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#1A1F36',
    marginBottom: 5,
  },
  aiInsightText: {
    fontSize: 9,
    color: '#4C1D95',
  },
});
