
import { StyleSheet } from '@react-pdf/renderer';

export const portfolioStyles = StyleSheet.create({
  // Enhanced Portfolio Glance Section
  portfolioGlance: {
    backgroundColor: '#F0FDF4',
    padding: 35,
    borderRadius: 20,
    marginBottom: 40,
    borderWidth: 4,
    borderColor: '#00B47B',
    borderLeftWidth: 8,
    borderLeftColor: '#2E7DFF',
  },
  glanceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
  },
  glanceTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1A1F36',
    letterSpacing: 0.5,
  },
  aiBadge: {
    backgroundColor: '#2E7DFF',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  aiBadgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  glanceGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 25,
  },
  glanceCard: {
    backgroundColor: '#FFFFFF',
    padding: 25,
    borderRadius: 15,
    flex: 1,
    marginHorizontal: 8,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  glanceLabel: {
    fontSize: 13,
    color: '#6B7280',
    marginBottom: 12,
    textAlign: 'center',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  glanceValue: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1A1F36',
    marginBottom: 8,
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  trendIndicator: {
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  sparklineContainer: {
    alignItems: 'center',
    marginVertical: 4,
  },
  glanceSubtext: {
    fontSize: 11,
    color: '#9CA3AF',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  xirrExplanation: {
    backgroundColor: '#EBF8FF',
    padding: 15,
    borderRadius: 10,
    marginBottom: 25,
    borderLeftWidth: 4,
    borderLeftColor: '#2E7DFF',
  },
  xirrNote: {
    fontSize: 11,
    color: '#1E40AF',
    lineHeight: 1.4,
    textAlign: 'center',
    fontStyle: 'italic',
  },

  // Goal Progress Section
  goalProgress: {
    backgroundColor: '#FFFFFF',
    padding: 25,
    borderRadius: 15,
    marginBottom: 25,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderTopWidth: 4,
    borderTopColor: '#00B47B',
  },
  goalProgressTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1A1F36',
    marginBottom: 20,
    textAlign: 'center',
  },
  goalProgressContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  goalProgressItem: {
    flex: 1,
    alignItems: 'center',
  },
  goalProgressLabel: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 8,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  goalProgressValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1A1F36',
  },

  // Performance Section - Enhanced Design
  performanceSection: {
    backgroundColor: '#FFFFFF',
    padding: 25,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderTopWidth: 4,
    borderTopColor: '#FFB800',
  },
  performanceTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1A1F36',
    marginBottom: 20,
    textAlign: 'center',
  },
  performanceGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  performanceItem: {
    flex: 1,
    alignItems: 'center',
  },
  performanceLabel: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 8,
    fontWeight: 'bold',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  performanceValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2E7DFF',
  },
});
