import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { reportType, clientCode, category, reportName, format = 'pdf' } = await req.json();
    
    console.log('PDF Shift generation request:', { reportType, clientCode, category, reportName });
    
    // Get the PDF Shift API key and validate it
    const pdfShiftApiKey = Deno.env.get('PDFSHIFT_API_KEY');
    if (!pdfShiftApiKey) {
      console.error('PDF Shift API key not found in environment');
      throw new Error('PDF Shift API key not configured');
    }
    console.log('PDF Shift API key found:', pdfShiftApiKey.substring(0, 8) + '...');

    // Debug: log the request to understand what's happening
    console.log('PDF Shift request:', { reportType, clientCode, category, reportName });

    // Create the most basic HTML to test PDF generation
    const htmlContent = `<html>
<head>
    <title>Test PDF</title>
</head>
<body>
    <h1>SIP Brewery - ${category.toUpperCase()} Statement</h1>
    <p><strong>Report:</strong> ${reportName}</p>
    <p><strong>Client Code:</strong> ${clientCode}</p>
    <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>
    
    <h2>Portfolio Summary</h2>
    <p>This is a test ${category} report.</p>
    
    <table border="1" style="width: 100%; margin: 20px 0;">
        <tr>
            <td><strong>Total Investment</strong></td>
            <td>₹2,45,000</td>
        </tr>
        <tr>
            <td><strong>Current Value</strong></td>
            <td>₹2,89,500</td>
        </tr>
        <tr>
            <td><strong>Total Returns</strong></td>
            <td>+18.16%</td>
        </tr>
    </table>
    
    <h3>Key Points:</h3>
    <ul>
        <li>Portfolio performing well</li>
        <li>Diversified investments</li>
        <li>Regular SIP benefits</li>
    </ul>
    
    <p style="margin-top: 30px; font-size: 12px;">
        Generated by SIP Brewery on ${new Date().toLocaleDateString()}
    </p>
</body>
</html>`;
    
    console.log('Using HTML content for PDF generation');

    // PDF Shift configuration with correct API options
    const pdfShiftOptions = {
      source: htmlContent,
      format: 'A4',
      margin: '15mm',
      landscape: false,
      timeout: 30, // Maximum allowed timeout is 30 seconds
      delay: 3000  // Wait 3 seconds for content to fully load (in milliseconds)
    };

    console.log('Calling PDF Shift API with options:', JSON.stringify(pdfShiftOptions, null, 2));
    
    // Make request to PDF Shift API with correct authentication
    const pdfShiftResponse = await fetch('https://api.pdfshift.io/v3/convert/pdf', {
      method: 'POST',
      headers: {
        'X-API-Key': pdfShiftApiKey,  // Correct authentication method
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(pdfShiftOptions),
    });

    console.log('PDF Shift response status:', pdfShiftResponse.status);
    console.log('PDF Shift response headers:', Object.fromEntries(pdfShiftResponse.headers.entries()));

    if (!pdfShiftResponse.ok) {
      const errorText = await pdfShiftResponse.text();
      console.error('PDF Shift API error:', pdfShiftResponse.status, errorText);
      throw new Error(`PDF generation failed: ${pdfShiftResponse.status} - ${errorText}`);
    }

    // Get the PDF as binary data
    const pdfArrayBuffer = await pdfShiftResponse.arrayBuffer();
    const pdfBytes = new Uint8Array(pdfArrayBuffer);
    console.log('PDF generated successfully, size:', pdfBytes.length, 'bytes');

    // Generate filename
    const timestamp = new Date().toISOString().slice(0, 10);
    const categoryName = category.charAt(0).toUpperCase() + category.slice(1);
    const filename = `${categoryName}_Statement_${clientCode}_${timestamp}.pdf`;

    // Return the PDF with proper headers
    return new Response(pdfBytes, {
      headers: {
        ...corsHeaders,
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': pdfBytes.length.toString(),
      },
    });

  } catch (error) {
    console.error('Error in PDF Shift generation:', error);
    
    return new Response(
      JSON.stringify({ 
        error: 'PDF generation failed', 
        details: error.message,
        timestamp: new Date().toISOString()
      }),
      { 
        status: 500, 
        headers: { 
          ...corsHeaders, 
          'Content-Type': 'application/json' 
        } 
      }
    );
  }
});