import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { reportType, clientCode, category, reportName, format = 'pdf' } = await req.json();
    
    console.log('PDF Shift generation request:', { reportType, clientCode, category, reportName });
    
    // Get the PDF Shift API key and validate it
    const pdfShiftApiKey = Deno.env.get('PDFSHIFT_API_KEY');
    if (!pdfShiftApiKey) {
      console.error('PDF Shift API key not found in environment');
      throw new Error('PDF Shift API key not configured');
    }
    console.log('PDF Shift API key found:', pdfShiftApiKey.substring(0, 8) + '...');

    // Debug: log the request to understand what's happening
    console.log('PDF Shift request:', { reportType, clientCode, category, reportName });

    // Create HTML content with proper structure and inline styles
    const htmlContent = `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>SIP Brewery Statement</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            margin: 40px; 
            font-size: 14px; 
            line-height: 1.6;
        }
        h1 { 
            color: #2563eb; 
            border-bottom: 2px solid #2563eb; 
            padding-bottom: 10px; 
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin: 20px 0; 
        }
        th, td { 
            border: 1px solid #ddd; 
            padding: 12px; 
            text-align: left; 
        }
        th { 
            background-color: #f8f9fa; 
            font-weight: bold; 
        }
        .header-info { 
            background-color: #f0f9ff; 
            padding: 15px; 
            border-radius: 5px; 
            margin: 20px 0; 
        }
    </style>
</head>
<body>
    <h1>SIP Brewery - ${category.toUpperCase()} Statement</h1>
    
    <div class="header-info">
        <p><strong>Report Type:</strong> ${reportName}</p>
        <p><strong>Client Code:</strong> ${clientCode}</p>
        <p><strong>Generated Date:</strong> ${new Date().toLocaleDateString('en-IN')}</p>
        <p><strong>Generated Time:</strong> ${new Date().toLocaleTimeString('en-IN')}</p>
    </div>
    
    <h2>Portfolio Summary</h2>
    <p>This is your comprehensive ${category} report generated by SIP Brewery.</p>
    
    <table>
        <thead>
            <tr>
                <th>Metric</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Total Investment</td>
                <td>₹2,45,000</td>
            </tr>
            <tr>
                <td>Current Value</td>
                <td>₹2,89,500</td>
            </tr>
            <tr>
                <td>Total Returns</td>
                <td style="color: #16a34a; font-weight: bold;">+₹44,500 (+18.16%)</td>
            </tr>
            <tr>
                <td>Investment Period</td>
                <td>24 months</td>
            </tr>
        </tbody>
    </table>
    
    <h3>Key Highlights:</h3>
    <ul>
        <li>Portfolio showing strong positive returns</li>
        <li>Well-diversified across multiple fund categories</li>
        <li>Regular SIP investments maintaining discipline</li>
        <li>Risk-adjusted returns within expected range</li>
    </ul>
    
    <hr style="margin: 30px 0; border: none; border-top: 1px solid #ddd;">
    
    <p style="font-size: 12px; color: #666; text-align: center;">
        Generated by SIP Brewery on ${new Date().toLocaleDateString('en-IN')} at ${new Date().toLocaleTimeString('en-IN')}<br>
        This document is computer generated and does not require signature.
    </p>
</body>
</html>`;
    
    console.log('Using HTML content for PDF generation');

    // PDF Shift configuration with correct API options
    const pdfShiftOptions = {
      source: htmlContent,
      format: 'A4',
      margin: '15mm',
      landscape: false,
      timeout: 30, // Maximum allowed timeout is 30 seconds
      delay: 3000  // Wait 3 seconds for content to fully load (in milliseconds)
    };

    console.log('Calling PDF Shift API with options:', JSON.stringify(pdfShiftOptions, null, 2));
    
    // Make request to PDF Shift API with correct authentication
    const pdfShiftResponse = await fetch('https://api.pdfshift.io/v3/convert/pdf', {
      method: 'POST',
      headers: {
        'X-API-Key': pdfShiftApiKey,  // Correct authentication method
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(pdfShiftOptions),
    });

    console.log('PDF Shift response status:', pdfShiftResponse.status);
    console.log('PDF Shift response headers:', Object.fromEntries(pdfShiftResponse.headers.entries()));

    if (!pdfShiftResponse.ok) {
      const errorText = await pdfShiftResponse.text();
      console.error('PDF Shift API error:', pdfShiftResponse.status, errorText);
      throw new Error(`PDF generation failed: ${pdfShiftResponse.status} - ${errorText}`);
    }

    // Get the PDF as binary data
    const pdfArrayBuffer = await pdfShiftResponse.arrayBuffer();
    const pdfBytes = new Uint8Array(pdfArrayBuffer);
    console.log('PDF generated successfully, size:', pdfBytes.length, 'bytes');

    // Generate filename
    const timestamp = new Date().toISOString().slice(0, 10);
    const categoryName = category.charAt(0).toUpperCase() + category.slice(1);
    const filename = `${categoryName}_Statement_${clientCode}_${timestamp}.pdf`;

    // Return the PDF with proper headers
    return new Response(pdfBytes, {
      headers: {
        ...corsHeaders,
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': pdfBytes.length.toString(),
      },
    });

  } catch (error) {
    console.error('Error in PDF Shift generation:', error);
    
    return new Response(
      JSON.stringify({ 
        error: 'PDF generation failed', 
        details: error.message,
        timestamp: new Date().toISOString()
      }),
      { 
        status: 500, 
        headers: { 
          ...corsHeaders, 
          'Content-Type': 'application/json' 
        } 
      }
    );
  }
});